language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: RxRdXJ5YMnB/y1aXAZQ6kqOX7lb+kkJhAr33JSAZ9WZFFE5sGHFCfCX9lo1AW+Un5d0Vshr7/E/tnst2uVWMdo2IoIgHCpypBwhjZ986p4ELDWww0HGybVmfu0xPgrPokLObY7uJJlEqJiC2RfNhSPrgcyeRbZdXFoE7wGZu8zNPGlDw1I1Z34hsgoSGhPQr8NTyHQg83SScjMfZLy+kv8y3c7yu6qWX+ngRh3ymJ/knm6TC9sslJrv3d2v2dUKUJF1AoF3ZCS5vAThC+yIlpKA6E5uC4UFESMeKgGMqtu1UysxOH3GDYFBPTDaY1DJylVeXKjZ/DvPCMoK2OvuTGWOY2raTwi6Uq5010yVtNAoYHTJM9kS4W7kblys2fnAWR7/PwGvxwb/oUS+AMH1FU90ewyjvWlU6q4s5B3ig8Uel2HsHmalMOBiDDKbMLrykSvgZU9FBh5NwLr1g0+5uE+W7MkV4ySbpRilKeMwtkVV6DyjButGCga/AiPQmWMNwAbH9gMcENHK6AXMFD5/epMSWnkDlQjQCRLgyk1tHe2CxNQnTpcL3qxi2bSrgPp4R4pONAIDYLnxO0I4e9n2zu0CBHIPdbNVe3gpEIdg8d0+NAuysWkRsiV6O7HQw3cnHcHduKOfmjXdVcDwfdlPAUbV849tk2PT8o6PaN2t1aGA=
  app: fierce-hamlet-9918
  on:
    repo: woodchucktest/flux-react-test
before_script:
 - npm install -g gulp
 - gulp build
